<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="Login Page Test" tests="4" failures="1" timestamp="11 Oct 2020 19:22:30 GMT" time="14.162" errors="0">
  <testcase name="verifyLoginPageTitle" time="5.013" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="verifyIfLinkTextIsDisplayedInLoginPageTest" time="0.492" classname="com.qa.hubspot.tests.LoginPageTest"/>
  <testcase name="verifyTextOfLoginPageTest" time="0.517" classname="com.qa.hubspot.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Â©2020 HubSpot, Inc. All Rights Reserved.] but found [©2020 HubSpot, Inc. All Rights Reserved.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Â©2020 HubSpot, Inc. All Rights Reserved.] but found [©2020 HubSpot, Inc. All Rights Reserved.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.qa.hubspot.tests.LoginPageTest.verifyTextOfLoginPageTest(LoginPageTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyTextOfLoginPageTest -->
  <testcase name="loginTest" time="0.589" classname="com.qa.hubspot.tests.LoginPageTest"/>
</testsuite> <!-- Login Page Test -->
